<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRkCTFFF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRkCTFFF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRkCTFFF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRkCTFFF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRkCTFFF\App_KernelDevDebugContainer([
    'container.build_hash' => 'RkCTFFF',
    'container.build_id' => '54a1fb6e',
    'container.build_time' => 1634127647,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRkCTFFF');
